server:
  port: 9004
eureka:
  client:
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: false #不注册到Eureka，不在注册中心显示
feign:
  hystrix:
    enabled: true #开启熔断支持